import {
  Instagram,
  Twitter,
  Facebook,
  Youtube,
  Linkedin,
  Github,
  Music,
  MessageCircle,
  Camera,
  Twitch,
  Globe,
  Mail,
} from "lucide-react"

export const socialPlatforms = [
  {
    id: "instagram",
    name: "Instagram",
    icon: Instagram,
    color: "#E4405F",
    placeholder: "https://instagram.com/username",
  },
  {
    id: "twitter",
    name: "Twitter/X",
    icon: Twitter,
    color: "#1DA1F2",
    placeholder: "https://twitter.com/username",
  },
  {
    id: "facebook",
    name: "Facebook",
    icon: Facebook,
    color: "#1877F2",
    placeholder: "https://facebook.com/username",
  },
  {
    id: "youtube",
    name: "YouTube",
    icon: Youtube,
    color: "#FF0000",
    placeholder: "https://youtube.com/@username",
  },
  {
    id: "linkedin",
    name: "LinkedIn",
    icon: Linkedin,
    color: "#0A66C2",
    placeholder: "https://linkedin.com/in/username",
  },
  {
    id: "github",
    name: "GitHub",
    icon: Github,
    color: "#333333",
    placeholder: "https://github.com/username",
  },
  {
    id: "tiktok",
    name: "TikTok",
    icon: Music,
    color: "#000000",
    placeholder: "https://tiktok.com/@username",
  },
  {
    id: "whatsapp",
    name: "WhatsApp",
    icon: MessageCircle,
    color: "#25D366",
    placeholder: "https://wa.me/1234567890",
  },
  {
    id: "snapchat",
    name: "Snapchat",
    icon: Camera,
    color: "#FFFC00",
    placeholder: "https://snapchat.com/add/username",
  },
  {
    id: "twitch",
    name: "Twitch",
    icon: Twitch,
    color: "#9146FF",
    placeholder: "https://twitch.tv/username",
  },
  {
    id: "website",
    name: "Website",
    icon: Globe,
    color: "#6B7280",
    placeholder: "https://yourwebsite.com",
  },
  {
    id: "email",
    name: "Email",
    icon: Mail,
    color: "#EA4335",
    placeholder: "mailto:your@email.com",
  },
]
